name = "NCNBD"
uuid = "76100c40-129e-4398-bc8a-8d92901b12c9"
authors = ["Christian Fuellner"]
version = "0.1.0"

[deps]
Delaunay = "07eb4e4e-0c6d-46ef-bc4e-83d5e5d860a9"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
PiecewiseLinearOpt = "0f51c51e-adfa-5141-8a04-d40246b8977c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SDDP = "f4570300-c277-11e8-125c-4912f86ce65d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
